# Exmple File : /usr/share/doc/alacritty/examples/alacritty.yml
import:
  - /home/nihil/.cache/wal/colors-alacritty.yml
## Window
window:
    dimensions:
        columns: 134
        lines: 30
    padding:
        x: 5
        y: 5
    class:
        instance: Alacritty
        general: Alacritty
    opacity: 0.9
scrolling:
    history: 10000
    multiplier: 3

## Colors
#colors:
#    primary:
#        background: "#1e1e2e"
#        foreground: "#cdd6f4"
#        dim_foreground: "#7f849c"
#        bright_foreground: "#cdd6f4"
#    cursor:
#        text: "#1e1e2e"
#        cursor: "#f5e0dc"
#    vi_mode_cursor:
#        text: "#1e1e2e"
#        cursor: "#b4befe"
#    search.matches:
#        foreground: "#1e1e2e"
#        background: "#a6adc8"
#    search.focused_match:
#        foreground: "#1e1e2e"
#        background: "#a6e3a1"
#    footer_bar:
#        foreground: "#1e1e2e"
#        background: "#a6adc8"
#    hints.start:
#        foreground: "#1e1e2e"
#        background: "#f9e2af"
#    hints.end:
#        foreground: "#1e1e2e"
#        background: "#a6adc8"
#    selection:
#        text: "#1e1e2e"
#        background: "#f5e0dc"
#    normal:
#        black: "#45475a"
#        red: "#f38ba8"
#        green: "#a6e3a1"
#        yellow: "#f9e2af"
#        blue: "#89b4fa"
#        magenta: "#f5c2e7"
#        cyan: "#94e2d5"
#        white: "#bac2de"
#    bright:
#        black: "#585b70"
#        red: "#f38ba8"
#        green: "#a6e3a1"
#        yellow: "#f9e2af"
#        blue: "#89b4fa"
#        magenta: "#f5c2e7"
#        cyan: "#94e2d5"
#        white: "#a6adc8"
#    colors.dim:
#        black: "#45475a"
#        red: "#f38ba8"
#        green: "#a6e3a1"
#        yellow: "#f9e2af"
#        blue: "#89b4fa"
#        magenta: "#f5c2e7"
#       cyan: "#94e2d5"
#        white: "#bac2de"
## Fonts
font:
    normal:
        family: Hack
        style: Medium
    bold:
        family: Hack
        style: Bold
    italic:
        family: Hack
        style: Italic
    bold_italic:
        family: Hack
        style: BoldItalic
    size: 10
draw_bold_text_with_bright_colors: true

## Cursor
cursor:
    style:
        shape: Beam
        blinking: off
        blink_interval: 750

## Shell
#shell:
#    program: /usr/bin/fish
