import = ["~/.cache/wal/colors-alacritty.toml"]

[font]
size = 12.0

[font.bold]
family = "MesloLGSNerdFont"
style = "Bold"

[font.bold_italic]
family = "MesloLGSNerdFont"
style = "Bold Italic"

[font.italic]
family = "MesloLGSNerdFont"
style = "Italic"

[font.normal]
family = "MesloLGSNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

#[window.dimensions]
#columns = 134
#lines = 30

[window.padding]
x = 5
y = 5
